baseURL = "http://example.org/"
languageCode = "en-us"
title = "Hugo Single Course Prototype"
theme = "hugo-course-publisher/site/themes/standalone_course"
[module]
  [[module.imports]]
    ignoreConfig = true
    path = "hugo-course-publisher/site"
  [[module.imports]]
    path = "hugo-course-publisher/site/themes/standalone_course"